### ISSUE TITLE
Soportar reproducir el episodio a través de chromecast

### ISSUE THREAD

**Issue by aitorpazos** [LaCafetera/LacAPPfetera#1]
Muchas gracias por el esfuerzo!

Sería genial si pudiéramos enviar el episodio en reproducción a dispositivos que soporten chromecast.

**Comment by McZhy** [comment]
Hola. 

Lo cierto es que lo estamos mirando, es una de las cosas que tenemos planificado incluir en próximas versiones.

Gracias por comentar.
